import Header from "@/_components/Header";
import Footer from "@/_components/Footer";
import "@/_style/bootstrap.min.css"
import "@/_style/fontawesome.min.css"
import "@/_style/magnific-popup.min.css"
import "@/_style/slick.min.css"
import "@/_style/layerslider.min.css"
import "@/_style/style.css"

export const metadata = {
  title: "The Ozark & Co. | Home",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/assets/img/favicons/favicon-96x96.png" type="image/x-icon" />
        <link rel="preconnect" href="https://fonts.googleapis.com/" />
        <link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Exo:wght@400;500;600;700&amp;family=Fira+Sans:wght@400;500&amp;display=swap" rel="stylesheet" />
      </head>
      <body>
        {/* <Header />
        <Footer /> */}
        {children}
       
      </body>
    </html>
  );
}
